name: Kubernetes Javascript Client - Validation

on:
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]

jobs:
    build:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node: ['23', '22', '20', '18']
        name: Node ${{ matrix.node }} validation
        steps:
            - uses: actions/checkout@v4.2.2
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
            # Pre-check to validate that versions match between package.json
            # and package-lock.json. Needs to run before npm install
            - run: node version-check.js
            - run: npm ci
            - run: npm test
            - run: npm run lint
            - run: npm audit --audit-level=critical
            - run: npm run build-with-tests && npm run test-transpiled
            - name: Extract k8s version
              id: extract_version
              run: |
                  version=$(grep 'export KUBERNETES_BRANCH=' settings | cut -d '"' -f 2)
                  echo "setting kubernetes version to $KUBERNETES_V_STRING"
                  echo "KUBERNETES_V_STRING=$version" >> "$GITHUB_ENV"
            - name: Start Minikube
              uses: medyagh/setup-minikube@latest
              id: minikube
              with:
                  minikube-version: ${{ env.KUBERNETES_V_STRING }}
                  driver: none
